apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=   # base64 of "password"
  MYSQL_USER: YXBwdXNlcg==           # base64 of "appuser"
  MYSQL_PASSWORD: YXBwcGFzcw==       # base64 of "apppass"
