apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: app
        image: movie:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
        ports:
        - containerPort: 8083
